# Generated by Django 3.2.7 on 2021-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(),
        ),
    ]
