# Generated by Django 3.2.7 on 2021-10-10 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('collects', '0002_alter_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='collection_id',
            new_name='collection',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='category_id',
        ),
        migrations.AddField(
            model_name='collect',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collects', to='categories.category'),
        ),
    ]
